version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    container_name: mongo_db_express
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app:
    image: morozovd/yahoo-scrape:latest
    container_name: python_application
    build: .
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always
    